version: '1'

services:
  mysql:
    image: mysql:latest
    container_name: mysqldb
    environment:
      MYSQL_ROOT_PASSWORD: 12345
      MYSQL_DATABASE: db1
      MYSQL_USER: luis
      MYSQL_PASSWORD: luis123
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
