import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { SidebarComponent } from "@/components/navComponents/Sidebar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex gap-2">
        <SidebarComponent/>
        {children}
        </div>
        </body>
    </html>
  );
}
